extends: airbnb-base
rules:
  semi:
    - error
    - never
  comma-dangle:
    - error
    - always-multiline
  no-use-before-define:
    - error
    - functions: false
  no-restricted-syntax:
    - off
